name = "IwaiEngine"
uuid = "5715ea1d-2681-4c29-8656-382bac65f29d"
authors = ["t-chen <tepelchen501@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
